# Laurux-Pos local configuration
[Coul]
Fnets="Background: &HDDDDDD&; "
Btns="Background: &HBDBDBD&; "
Znss="Background: &HFAFAFA&; "
Znaff="Background: &HEEEEEE&; "
Focus="Background: &HF9FFC7&; "
Coulfonds="Background: &FFEE81&; "
Others="Background: &FFE0B8&; "

[General]
Soc="01"
intitule="  "
son=0
Tips=1
tactile=0

[Soc01]
Entete=1
Conditions=1
Tva550=0
Codetva=" "
Compta=0
Gestion=0
CptFac=1
Qt1=0
Coul_fen=0
Ctrlstk=0
AutoEnt=0
Copie=0
Siret="Siret"
Prxdec=0
Taxe="TVA"

[dbase]
Version="Laurux-Pos V3.25"
type="mysql"
Name="Laurux01"
Login="laurux"
Password="2D0D0D0D0D0D"
Port="3306"
Cnl=0
Host="127.0.0.1"
Con-ssh=0

[dbase/ssh]
Con-ssh=0

