# Laurux local configuration
[Coul]
Fnets="Background: &HDDDDDD&; "
Btns="Background: &HBDBDBD&; "
Znss="Background: &HFAFAFA&; "
Znaff="Background: &HEEEEEE&; "
Focus="Background: &HF9FFC7&; "
Coulfonds="255,252,216,"
Others="255,232,199,"
Fcs="Background: &HF9FFC7&"
Stk="Background: &HCFF58E&; Font: serif,9; "
Facts="Background: &HFFFFFF&; Font: Serif,9; "
Avs="Background: &HFFFFFF&; Font: Serif,9; "
Bl="Background: &HFFFFFF&; Font: Serif,9; "
Devis="Background: &HFFFFFF&; Font: Serif,9; "
Devis2="Background: &HFFFFFF&; Font: Serif,9; "
Cmde="Background: &HFFFFFF&; Font: Serif,9; "
Prf="Background: &HFFFFFF&; Font: Serif,9; "
Nstk="Background: &HFFFFFF&; Font: Serif,9; "
Eps="Background: &HFFFFFF&; Font: Serif,9; "
Spd="Background: &HFFFFFF&; Font: Serif,9; "
Motps="Background: &HFFFFFF&; Font: Serif,9; "
Momnt="Background: &HFFFFFF&; Font: Serif,9; "

[General]
Soc="01"
intitule="  "
son=0
Tips=1

[Soc]
Exp=1
Lettrage=1
Impbl=0

[Soc01]
Entete=1
Conditions=1
Tva550=0
Codetva=" "
Compta=0
Gestion=0
CptFac=1
Qt1=0
Coul_fen=0
Ctrlstk=0
AutoEnt=0
Font="Serif,+1"
Copie=0
Siret="Siret"
Prxdec=0
Taxe="TVA"
Pays="France"
Impbl=0
nbfam="5"
ipr=[5]
pp=False
bois=False
Ecran="896;632"

[dbase]
type="mysql"
Name="Laurux01"
Login="laurux"
Password="2D0D0D0D0D0D"
Port="3306"
Host="127.0.0.1"
Maj=-1
Con-ssh=0
Version="Laurux V3.59"

[dbase/ssh]
Con-ssh=0

