' Gambas module file

'*********************************************
'*        Recherche de l'éditeur             *
'* Procedure inspirée par Benoit Minisini  *
'*********************************************

Public Enum FILE_TYPE_TXT, FILE_TYPE_PDF, FILE_TYPE_MAX

Public Sub Prog_Editeur(Fic As String, Optional Type As Integer = FILE_TYPE_TXT) As String

  Dim $Exec As String

  If Start.LocalSettings["/CmdEditor" & Type] Then
    Shell Start.LocalSettings["/CmdEditor" & Type] & " " & Fic
  Else
    Desktop.Open(Fic)
  Endif

End

Public Sub Prog_Email(Fic As String) As String

  Dim $Exec As String

  $Exec = "thunderbird"
  If Not CheckProg.Chk($Exec) Then $Exec = "kmail"
  If Not CheckProg.Chk($Exec) Then $Exec = "evolution"

End
