' Gambas module file

Public spiece As String
Public schemin As String

Public Sub Dupli(Fichier As String, chemin As String, ty As String, Dtef As String)

  If Not Exist(User.home & chemin) Then
    Try Mkdir User.home & chemin
    If Error Then
      Message.Error("Problème lors de la création d'un répertoire\nMerci de créer manuellement un répertoire nommé 'Impressions'")
    Endif
  Else
    Try spiece = ""
    Shell "cd " & User.Home & "" Wait
    Shell "cp " & Fichier & " " & User.Home & chemin & "/" & ty & ".pdf" Wait
    spiece = User.Home & chemin & "/" & ty & ".pdf"
    schemin = User.Home & chemin & "/"
    Wait 0.5
  Endif

End

