' Gambas module file

Public Sub Ticket(Fic As String, nb As Integer) As String

  Dim $Exec As String

  Shell "cd " & User.Home & ""
  If Start.LocalSettings["/TKpdf"] Then
    Visualiseur.Prog(Fic)
  Endif
  
  If Start.LocalSettings["/CmdImp"] Then
    $Exec = Start.LocalSettings["/CmdImp"]
  Else
    $Exec = "lpr"
  Endif
  
  If Not IsNull(Start.LocalSettings["/Cimp"]) Then
    Shell $Exec & " -P " & Start.LocalSettings["/Cimp"] & " -# " & nb & " " & Fic Wait
  Else
    Shell $Exec & " -# " & nb & " " & Fic Wait
  Endif

End


Public Sub Facture(Fic As String, nb As Integer, Optional Imprimante As String = "") As String

  Dim $Exec As String
  Dim i As Integer
  
  Shell "cd " & User.Home & ""
  If Start.LocalSettings["/FACpdf"] Then
    Visualiseur.Prog(Fic)
  Endif
  
  If Start.LocalSettings["/CmdImp"] Then
    $Exec = Start.LocalSettings["/CmdImp"]
  Else
    $Exec = "lpr"
  Endif
  If Start.LocalSettings["/choiximp2"] Then
    $Exec = $Exec & " " & Fic 'Wait
  Else
    If Not IsNull(Imprimante) Then
      $Exec = $Exec & " -P " & Imprimante & " " & Fic 
    Else If Not IsNull(Start.LocalSettings["/Cimp"]) Then
      $Exec = $Exec & " -P " & Start.LocalSettings["/Cimp"] & " " & Fic 
    Else
      $Exec = $Exec & " " & Fic
    Endif
    For i = 1 To nb
      Shell $Exec Wait
    Next
  Endif

End
